planner/urls.py
from django.urls import path

from . import views

app_name = 'planner'
urlpatterns = [
    path('', views.UserSelectView.as_view(), name='userselect'),
    path('<slug:slug>/', views.ProfileView.as_view(), name='profile'),
    path('<slug:slug>/<int:pk>', views.NoteDetailView.as_view(), name='note_detail'),
    path('<slug:slug>/new_note/', views.get_note, name='new_note'),
    path('<slug:slug>/<int:pk>/delete/', views.del_note, name='del_note'),
    path('<slug:slug>/calendar/<int:pYear>/<int:pMonth>', views.calendar, name ='calendar')
]

"""
<slug:slug> allows you to have a slug field
that contains the url portion in the view field
"""

planner/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify


class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birthday = models.DateField(default=timezone.now)
    motto = models.CharField(max_length=200, default='What is your motto?')
    slug = models.SlugField()

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    # doesnt handle duplicate slugs
    def save(self, *args, **kwargs):
        if not self.id:
            #newly created so set slu
            slug_str = "%s %s" % (self.first_name, self.last_name)
            self.slug = slugify(slug_str)
        super(User, self).save(*args, **kwargs)


class Note(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=500)
    post_date = models.DateField('date posted',default=timezone.now)
    expr_date = models.DateTimeField('expiration date', default=timezone.now)
    priority = models.IntegerField(default=-1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        if not self.id:
            #newly created so set slug
            self.slug = slugify(self.title)
        super(Note, self).save(*args, **kwargs)

    def __str__(self):
        return self.title + ': ' + self.content

    def expired(self):
        now = timezone.now()
        return self.expr_date < now

    def expiring_within_week(self):
        now = timezone.now()
        return (not self.expired()) and (
                now + datetime.timedelta(days=7) >= self.expr_date)

planner/forms.py
from django import forms

from .models import Note

class DeleteNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = []

class CreateNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content', 'expr_date']

planner/views.py
from itertools import groupby
from datetime import date, datetime
from calendar import monthrange

from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect

from .models import User, Note
from .forms import CreateNoteForm, DeleteNoteForm


class UserSelectView(generic.ListView):
    template_name = 'planner/userselect.html'
    context_object_name = 'user_list'
    def get_queryset(self):
        return User.objects.all()


class ProfileView(generic.DetailView):
    model = User
    template_name = 'planner/profile.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['year'] = timezone.now().year
        context['month'] = timezone.now().month
        return context

class NoteDetailView(generic.DetailView):
    model = Note
    template_name = 'planner/note_detail.html'
    context_object_name = 'note'


def del_note(request, pk, **kwargs):
    note_to_delete = get_object_or_404(Note, id=pk)
    # todo - check user and note_id
    if request.method == 'POST':
        form = DeleteNoteForm(request.POST, instance=note_to_delete)
        if form.is_valid(): # check csrf
            note_to_delete.delete()
            return HttpResponseRedirect("../..") # where to go
    else:
        form = DeleteNoteForm(instance=note_to_delete)
    template_vars = {'form': form, 'note': note_to_delete}
    return render(request, 'planner/del_note.html', template_vars)


def get_note(request, slug, **kwargs):
    # Must ensure slug uniqueness
    usr = User.objects.get(slug=slug)
    if request.method == 'POST':
        form = CreateNoteForm(request.POST)
        if form.is_valid():
            n = form.save(commit=False)
            n.user = usr
            n.save()
            return HttpResponseRedirect('..')
    else:
        form = CreateNoteForm()

    return render(request, 'planner/note.html', {'form': form})


def month_name(pMonthNumber):
    """
    Return the name of the month, given the number.
    """
    return date(1900, pMonthNumber, 1).strftime("%B")


def this_month(request):
    """
    Show calendar of notes this month.
    """
    today = datetime.now()
    return calendar(request, today.year, today.month)


def calendar(request, slug, pYear, pMonth, pNoteType=None, **kwargs):
    """
    Show calendar of notes for a given month of a given year.
    pNoteType denotes type of note to display
    """

    lYear = int(pYear)
    lMonth = int(pMonth)
    calendar_from_month = datetime(pYear, pMonth, 1)
    calendar_to_month = datetime(pYear, pMonth, monthrange(pYear, pMonth)[1])
    this_user = User.objects.get(slug=slug) # retrieves only notes for user
    lNoteEvents = Note.objects.filter(user=this_user)
    lNoteEvents = lNoteEvents.filter(expr_date__gte=calendar_from_month)
    lNoteEvents = lNoteEvents.filter(expr_date__lte=calendar_to_month)
    # Note types are not implemented yet
    if pNoteType is not None:
        lNoteEvents = lNoteEvents.filter(type=pNoteType)

    # Calculate values for the calendar controls. 1-indexed (Jan = 1)
    lPreviousYear = lYear
    lPreviousMonth = lMonth - 1
    if lPreviousMonth == 0:
        lPreviousYear = lYear - 1
        lPreviousMonth = 12
    lNextYear = lYear
    lNextMonth = lMonth + 1
    if lNextMonth == 13:
        lNextYear = lYear + 1
        lNextMonth = 1
    lYearAfterThis = lYear + 1
    lYearBeforeThis = lYear - 1
    return render(request,"planner/calendar.html", {
            'note_list': lNoteEvents,
            'month': lMonth,
            'month_name': month_name(lMonth),
            'year': lYear,
            'prev_month_name': month_name(lPreviousMonth),
            'prev_month': lPreviousMonth,
            'prev_year': lPreviousYear,
            'next_month': lNextMonth,
            'next_month_name': month_name(lNextMonth),
            'next_year': lNextYear,
            'year_before_this': lYearBeforeThis,
            'year_after_this': lYearAfterThis,
            'slug':slug
    })

planner/templates/planner/calendar.html
{% load calendar %}

<table width="100%">
  <tr>
    <td width="20%" align="left">
      &lt;&lt;
      <a href="{% url 'planner:calendar' slug year_before_this month %}">
        {{month_name}} {{year_before_this}}
      </a>
    </td>
    <td width="20%" align="left">
      &lt;&lt;
      <a href="{% url 'planner:calendar' slug prev_year prev_month %}">
        {{prev_month_name}} {{prev_year}}
      </a>
    </td>
    <td width="20%" align="center">
      <a>
        Today
      </a>
    </td>
    <td width="20%" align="right">
      <a href="{% url 'planner:calendar' slug next_year next_month %}">
        {{next_month_name}} {{next_year}}
      </a>
      &gt;&gt;
    </td>
    <td width="20%" align="right">
      <a href="{% url 'planner:calendar' slug year_after_this month %}">
        {{month_name}} {{year_after_this}}
      </a> &gt;&gt;
    </td>
  </tr>
</table>
<div id="calendar">
	{% note_calendar year month note_list %}
</div>
<button>
  <a href="{% url 'planner:profile' slug %}">
    Return to profile
  </a>
</button>

planner/templates/planner/del_note.html
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Delete?" />
</form>
<button>
  <a href="{% url 'planner:note_detail' note.user.slug note.id %}">
    Cancel
  </a>
</button>

planner/templates/planner/note.html
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Save" />
</form>

planner/templates/planner/note_detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<dl>
  <dt>
    {{note.title}}
  </dt>
  <dd>
    {{note.message}}
  </dd>
  <dt>
    Until {{note.expr_date}}
  </dt>
  <dt>
    Priority: {{note.priority}}
  </dt>
</dl>

<button type="button">
  <a href="{% url 'planner:del_note' note.user.slug note.id %}">
    Delete
  </a>
</button>

<button>
  <a href = "{% url 'planner:profile' note.user.slug %}">
    Return
  </a>
</button>

planner/templates/planner/profile.html
<h1>{{ user }}</h1>
{{user.motto}}
<p>Note list:</p>
{% if user.note_set.all %}
  {% for note in user.note_set.all %}
    <li>
      <a href="{% url 'planner:note_detail' user.slug note.id %}">
        {{note}}
      </a>
    </li>
  {% endfor %}
{% else %}
  <p>No notes have been made</p>
{% endif %}


<button type="button">
  <a href="{% url 'planner:new_note' user.slug %}">
    Create Note
  </a>
</button>

<button>
  <a href="{% url 'planner:userselect' %}">
    Return to user select
  </a>
</button>

<button>
  <a href="{% url 'planner:calendar' user.slug year month %}">
    Calendar
  </a>
</button>

planner/templates/planner/userselect.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if user_list %}
  <ul>
    {% for user in user_list %}
      <li>
        <a href="{% url 'planner:profile' user.slug %}">
          {{ user }}
        </a>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No registered users</p>
{% endif %}